# Generated by Django 5.0.6 on 2024-07-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
