# Generated by Django 5.0.6 on 2024-09-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_expense_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="budget",
        ),
    ]
