# Generated by Django 5.0.6 on 2024-07-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_expensecategory_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensecategory",
            name="type",
            field=models.CharField(
                choices=[("wants", "Wants"), ("needs", "Needs")],
                default="needs",
                max_length=100,
            ),
        ),
    ]
