# Generated by Django 5.0.6 on 2024-09-19 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets_manager", "0007_remove_monthlyincomes_total_income"),
        ("expenses", "0003_remove_expense_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="budget",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="budgets_manager.budgetmanager",
            ),
            preserve_default=False,
        ),
    ]
