# Generated by Django 5.0.6 on 2024-07-05 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_alter_expense_user_alter_expensecategory_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["user"], name="expenses_ex_user_id_51d8ba_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["datetime"], name="expenses_ex_datetim_967b90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category"], name="expenses_ex_categor_20264a_idx"
            ),
        ),
    ]
