# Generated by Django 5.0.6 on 2024-08-06 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_manager",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets_manager.budgetmanager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollaborationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collaboration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="multi_user.collaboration",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collaboration",
            name="users",
            field=models.ManyToManyField(
                related_name="collaborations",
                through="multi_user.CollaborationUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(help_text="Enter Email", max_length=254)),
                (
                    "token",
                    models.CharField(help_text="Token", max_length=100, unique=True),
                ),
                (
                    "accepted",
                    models.BooleanField(default=False, help_text="Is accepted..."),
                ),
                (
                    "collaboration",
                    models.ForeignKey(
                        help_text="Enter collaborations...",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="multi_user.collaboration",
                    ),
                ),
            ],
        ),
    ]
