# Generated by Django 5.0.6 on 2024-08-05 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(help_text="Enter Email", max_length=254)),
                (
                    "token",
                    models.CharField(help_text="Token", max_length=100, unique=True),
                ),
                (
                    "accepted",
                    models.BooleanField(default=False, help_text="Is accepted..."),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Enter budget manager...",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets_manager.budgetmanager",
                    ),
                ),
            ],
        ),
    ]
