# Generated by Django 5.0.6 on 2024-09-12 12:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets_manager", "0001_initial"),
        ("multi_user", "0003_alter_collaboration_options_collaboration_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="collaboration",
        ),
        migrations.CreateModel(
            name="FamilyBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_manager",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets_manager.budgetmanager",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="family_budgets", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_family_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvitationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the person invited", max_length=254
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                (
                    "family_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="multi_user.familybudget",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Collaboration",
        ),
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
