# Generated by Django 5.0.6 on 2024-09-17 10:00

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multi_user", "0004_remove_invitation_collaboration_familybudget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="familybudget",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="familybudget",
            name="title",
            field=models.CharField(default="Family", max_length=50, unique=True),
        ),
    ]
