# Generated by Django 5.0.6 on 2024-09-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multi_user", "0006_alter_familybudget_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familybudget",
            name="owner",
        ),
        migrations.AlterField(
            model_name="familybudget",
            name="title",
            field=models.CharField(default="Family", max_length=50),
        ),
    ]
