# Generated by Django 5.0.6 on 2024-09-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets_manager", "0005_alter_setbudget_user"),
        ("multi_user", "0007_remove_familybudget_owner_alter_familybudget_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitationtoken",
            name="family_budget",
        ),
        migrations.AddField(
            model_name="invitationtoken",
            name="budget",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="budgets_manager.budgetmanager",
            ),
            preserve_default=False,
        ),
    ]
