# Generated by Django 5.0.6 on 2024-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multi_user", "0008_remove_invitationtoken_family_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationtoken",
            name="is_used",
            field=models.BooleanField(
                default=False, help_text="Whether the token was used?"
            ),
        ),
        migrations.DeleteModel(
            name="FamilyBudget",
        ),
    ]
