# Generated by Django 5.0.6 on 2024-09-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multi_user", "0009_alter_invitationtoken_is_used_delete_familybudget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationtoken",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
