# Generated by Django 5.0.6 on 2024-05-31 15:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="image",
            field=models.ImageField(
                default="static/img/undraw_posting_photo.svg",
                upload_to=accounts.models.get_upload_path,
            ),
        ),
    ]
