# Generated by Django 5.0.6 on 2024-07-04 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saving",
            name="amount",
        ),
        migrations.AlterField(
            model_name="saving",
            name="date",
            field=models.DateField(
                auto_now_add=True, help_text="Date of the saving entry."
            ),
        ),
        migrations.AlterField(
            model_name="saving",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="SavingContributions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0, verbose_name="Savings amount")),
                (
                    "saving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="targets.saving",
                        verbose_name="Saving",
                    ),
                ),
            ],
        ),
    ]
