# Generated by Django 5.0.6 on 2024-07-05 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0002_remove_saving_amount_alter_saving_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
