# Generated by Django 5.0.6 on 2024-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0002_target_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="description",
            field=models.TextField(
                blank=True, help_text="A description of the target.", null=True
            ),
        ),
    ]
