# Generated by Django 5.0.6 on 2024-06-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0003_target_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="targetcontribution",
            options={"ordering": ("-date",)},
        ),
    ]
