# Generated by Django 5.0.6 on 2024-07-05 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0003_alter_target_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="targetcontribution",
            index=models.Index(fields=["user"], name="targets_tar_user_id_755e19_idx"),
        ),
        migrations.AddIndex(
            model_name="targetcontribution",
            index=models.Index(fields=["amount"], name="targets_tar_amount_c61e46_idx"),
        ),
        migrations.AddIndex(
            model_name="targetcontribution",
            index=models.Index(fields=["date"], name="targets_tar_date_f2960f_idx"),
        ),
    ]
