# Generated by Django 5.0.6 on 2024-07-12 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0007_alter_savingcontributions_negative_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="savingcontributions",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date of the contribution entry.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="saving",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saving",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
