# Generated by Django 5.0.6 on 2024-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0008_savingcontributions_date_alter_saving_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savingcontributions",
            options={"ordering": ("date",)},
        ),
        migrations.RemoveField(
            model_name="savingcontributions",
            name="negative_amount",
        ),
        migrations.RemoveField(
            model_name="savingcontributions",
            name="positive_amount",
        ),
        migrations.AddField(
            model_name="savingcontributions",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Enter the amount.",
                max_digits=10,
                verbose_name="Amount",
            ),
        ),
    ]
