# Generated by Django 5.0.6 on 2024-05-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(
                auto_now=True, help_text="Date and time when the income was recorded"
            ),
        ),
    ]
