# Generated by Django 5.0.6 on 2024-05-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0002_alter_income_options_alter_income_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(
                help_text="Date and time when the income was recorded"
            ),
        ),
    ]
