# Generated by Django 5.0.6 on 2024-05-17 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0003_alter_income_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time when the income was recorded",
            ),
        ),
    ]
