# Generated by Django 5.0.6 on 2024-08-06 11:51

import django.db.models.deletion
import django.utils.timezone
import subscription.fields.card_number
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter name of the plan.", max_length=120, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Enter description of the plan."),
                ),
                ("price", models.FloatField(help_text="Enter price of the plan.")),
            ],
            options={
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Enter first Name from your card.", max_length=50
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Enter last Name from your card.", max_length=50
                    ),
                ),
                (
                    "number",
                    subscription.fields.card_number.CreditCardNumberField(
                        help_text="Enter your credit card number.", max_length=19
                    ),
                ),
                (
                    "cvv",
                    models.CharField(help_text="Enter cvv of payment.", max_length=4),
                ),
                ("valid_thru", models.DateField(help_text="Enter valid thru date.")),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="The date when the subscription started.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="The date when the subscription ends. Automatically set to 30 days from the start date if not specified.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Select subscription plan.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this subscription.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date"],
                "get_latest_by": "end_date",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter payment amount",
                        max_digits=10,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Enter date of payment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        help_text="Status of the payment",
                        max_length=20,
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        help_text="Enter subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date"],
            },
        ),
    ]
