# Generated by Django 5.0.6 on 2024-07-25 14:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 25, 14, 22, 30, 686007, tzinfo=datetime.timezone.utc
                ),
                help_text="Enter date of payment",
            ),
        ),
    ]
