# Generated by Django 5.0.6 on 2024-07-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("Basic", "Basic"),
                    ("Standard", "Standard"),
                    ("Premium", "Premium"),
                ],
                default="Basic",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Plan",
        ),
    ]
