# Generated by Django 5.0.6 on 2024-07-25 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_alter_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Enter date of payment"
            ),
        ),
    ]
