# Generated by Django 5.0.6 on 2024-07-22 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_alter_subscription_plan_delete_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter name of the plan.", max_length=120, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Enter description of the plan."),
                ),
                ("price", models.FloatField(help_text="Enter price of the plan.")),
            ],
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="The date when the subscription ends. Automatically set to 30 days from the start date if not specified.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(
                auto_now_add=True, help_text="The date when the subscription started."
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                help_text="The user who owns this subscription.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                help_text="The subscription plan selected by the user.",
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.plan",
            ),
        ),
    ]
