# Generated by Django 5.0.6 on 2024-08-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_alter_payment_options_rename_date_payment_due_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"get_latest_by": "end_date", "ordering": ["-end_date"]},
        ),
    ]
