# Generated by Django 5.0.6 on 2024-07-25 10:50

import django.db.models.deletion
import subscription.fields.card_number
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_alter_plan_options_alter_subscription_plan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Enter first Name from your card", max_length=50
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Enter last Name from your card", max_length=50
                    ),
                ),
                (
                    "number",
                    subscription.fields.card_number.CreditCardNumberField(
                        help_text="Enter your credit card number", max_length=19
                    ),
                ),
                (
                    "cvv",
                    models.CharField(help_text="Enter cvv of payment", max_length=4),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter payment amount",
                        max_digits=10,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, help_text="Enter date of payment"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Enter subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
