# Generated by Django 5.0.6 on 2024-07-25 11:02

import django.utils.timezone
import subscription.fields.card_number
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0005_creditcard_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="valid_thru",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Enter valid thru date."
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="cvv",
            field=models.CharField(help_text="Enter cvv of payment.", max_length=4),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="first_name",
            field=models.CharField(
                help_text="Enter first Name from your card.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="last_name",
            field=models.CharField(
                help_text="Enter last Name from your card.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="number",
            field=subscription.fields.card_number.CreditCardNumberField(
                help_text="Enter your credit card number.", max_length=19
            ),
        ),
    ]
