# Generated by Django 5.0.6 on 2024-06-10 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0002_alter_expense_options_and_more"),
        ("runningCosts", "0009_runningcostcategory_user_alter_runningcost_user"),
        ("targets", "0006_saving"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Total monthly income.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "savings_percentage",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Percentage of the income allocated for savings.",
                        max_digits=5,
                    ),
                ),
                (
                    "wants_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of the income allocated for wants.",
                        max_digits=5,
                    ),
                ),
                (
                    "needs_percentage",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Percentage of the income allocated for needs.",
                        max_digits=5,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user this budget is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Planer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("wants", "Wants"),
                            ("needs", "Needs"),
                            ("save", "Save"),
                        ],
                        help_text="Type of budget category.",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount allocated to this budget entry.",
                        max_digits=20,
                    ),
                ),
                (
                    "budget_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets_manager.budgetmanager",
                    ),
                ),
                (
                    "category_expense",
                    models.ForeignKey(
                        blank=True,
                        help_text="Expense category for 'needs' type budget.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "category_running_cost",
                    models.ForeignKey(
                        blank=True,
                        help_text="Running cost category for 'needs' type budget.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="runningCosts.runningcostcategory",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target category for 'wants' type budget.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="targets.target",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
