# Generated by Django 5.0.6 on 2024-06-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets_manager", "0002_alter_planer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetmanager",
            name="monthly_income",
        ),
    ]
