# Generated by Django 5.0.6 on 2024-09-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "budgets_manager",
            "0002_budgetmanager_color_budgetmanager_participants_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetmanager",
            name="user",
            field=models.ForeignKey(
                help_text="The user this budget is associated with.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
