# Generated by Django 5.0.6 on 2024-06-19 12:56

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets_manager", "0004_needsmanager_savingmanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyIncomes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="Enter Year")),
                ("month", models.IntegerField(help_text="Enter Month")),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets_manager.budgetmanager",
                    ),
                ),
            ],
            options={
                "unique_together": {("budget", "year", "month")},
            },
        ),
    ]
