# Generated by Django 5.0.6 on 2024-06-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets_manager", "0004_needsmanager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NeedsManager",
        ),
    ]
