# Generated by Django 5.0.6 on 2024-06-19 13:36

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets_manager", "0005_monthlyincomes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthlyincomes",
            options={"ordering": ["budget", "year", "month"]},
        ),
        migrations.AlterField(
            model_name="monthlyincomes",
            name="month",
            field=models.IntegerField(
                blank=True,
                help_text="Enter Month",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="monthlyincomes",
            name="total_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlyincomes",
            name="year",
            field=models.IntegerField(blank=True, help_text="Enter Year", null=True),
        ),
    ]
