# Generated by Django 5.0.6 on 2024-09-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets_manager", "0005_alter_setbudget_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyincomes",
            name="total_income",
            field=models.IntegerField(default=0),
        ),
    ]
