# Generated by Django 5.0.6 on 2024-09-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets_manager", "0006_monthlyincomes_total_income"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyincomes",
            name="total_income",
        ),
    ]
