# Generated by Django 5.0.6 on 2024-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets_manager", "0007_remove_monthlyincomes_total_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyincomes",
            name="monthly_income",
            field=models.IntegerField(default=0),
        ),
    ]
