# Generated by Django 5.0.6 on 2024-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "budgets_manager",
            "0009_remove_limitmanager_unique_budget_category_running_cost_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="SavingManager",
        ),
        migrations.CreateModel(
            name="WantsManager",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("budgets_manager.budgetmanager",),
        ),
        migrations.AlterField(
            model_name="limitmanager",
            name="type",
            field=models.CharField(
                choices=[("wants", "Wants"), ("needs", "Needs")],
                help_text="Type of budget category.",
                max_length=10,
            ),
        ),
    ]
