# Generated by Django 5.0.6 on 2024-08-06 11:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunningCostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the category of the running coast.",
                        max_length=256,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter the category description.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunningCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "amount",
                    models.FloatField(
                        help_text="The amount of money for the running cost."
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("months", "Months"), ("years", "Years")],
                        default="months",
                        help_text="The type of period for the running cost (e.g., months, weeks).",
                        max_length=256,
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        help_text="The number of periods (e.g., 2 for bi-monthly).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "payment_deadline",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="The deadline for paying the running cost.",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the running cost has been paid or not.",
                    ),
                ),
                (
                    "next_payment_date",
                    models.DateField(
                        blank=True,
                        help_text="The next scheduled payment date.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="running_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="running_costs",
                        to="runningCosts.runningcostcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["next_payment_date"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="runningCost_user_id_f56fb9_idx"
                    ),
                    models.Index(
                        fields=["next_payment_date"],
                        name="runningCost_next_pa_2bec7b_idx",
                    ),
                ],
            },
        ),
    ]
