# Generated by Django 5.0.6 on 2024-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runningCosts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runningcost",
            name="period_type",
            field=models.CharField(
                choices=[("months", "Months"), ("years", "Years")],
                default="months",
                help_text="The type of period for the running cost (e.g., months, weeks).",
                max_length=256,
            ),
        ),
    ]
