# Generated by Django 5.0.6 on 2024-07-10 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runningCosts", "0003_alter_runningcost_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="runningcostcategory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
