# Generated by Django 5.0.6 on 2024-05-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runningCosts", "0004_remove_runningcost_due_date_runningcost_payment_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runningcost",
            name="payment_day",
        ),
        migrations.AddField(
            model_name="runningcost",
            name="is_overdue",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the payment is overdue."
            ),
        ),
        migrations.AddField(
            model_name="runningcost",
            name="next_payment_date",
            field=models.DateField(
                blank=True, help_text="The next scheduled payment date.", null=True
            ),
        ),
    ]
