# Generated by Django 5.0.6 on 2024-06-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runningCosts", "0007_alter_runningcost_period"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="runningcost",
            options={"ordering": ["next_payment_date"]},
        ),
    ]
